version: '3.2'
services:
  master:
    image: rancher/k3s:v1.20.0-k3s2
    tmpfs:
    - /run
    - /var/run
    privileged: true
    entrypoint: /start.sh
    environment:
    - K3S_KUBECONFIG_OUTPUT=/var/lib/rancher/k3s/kubeconfig.yaml
    volumes:
    - ./start.sh:/start.sh:ro
    - ${K3S_DATA-./data}:/var/lib/rancher/k3s
    network_mode: host
